-- 1. 'STUDENTS' 생성
CREATE TABLE students (
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    mobileNumber VARCHAR(11) NOT NULL,
    dateOfBirth VARCHAR(8) NOT NULL,
    gender CHAR(2) NOT NULL,
    school VARCHAR(20),
    grade CHAR(2),
    version INT,
    created DATE,
    updated DATE
) DEFAULT CHARSET = utf8;

-- 2. 'STUDENTS_PARENTS' 생성
CREATE TABLE STUDENTS_PARENTS (
    ID INT NOT NULL PRIMARY KEY,
    STUDENT_ID INT NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    MOBILE_NUMBER VARCHAR(11) NOT NULL,
    VERSION INT,
    CREATED DATE,
    UPDATED DATE,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(ID)
);


