-- 1. 'STUDENTS' 생성
CREATE TABLE STUDENTS (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '학생 ID',
    NAME VARCHAR(20) NOT NULL COMMENT '성명',
    MOBILE_NUMBER VARCHAR(11) NOT NULL COMMENT '휴대폰 번호',
    DATE_OF_BIRTH VARCHAR(8) NOT NULL COMMENT '생년월일',
    GENDER CHAR(2) NOT NULL COMMENT '성별 (M: 남성, F: 여성)',
    SCHOOL VARCHAR(20) COMMENT '학교',
    GRADE CHAR(2) COMMENT '학년',
    STATUS VARCHAR(10) NOT NULL COMMENT '상태 (ACTIVE: 정상, DELETED: 탈퇴)',
    VERSION INT COMMENT '수정 버전',
    CREATED DATE COMMENT '생성일',
    UPDATED DATE COMMENT '수정일'
) DEFAULT CHARSET = UTF8;

-- 2. 'STUDENTS_PARENTS' 생성
CREATE TABLE PARENTS (
    ID INT NOT NULL PRIMARY KEY COMMENT '학생 부모 ID',
    STUDENT_ID INT NOT NULL COMMENT '학생 ID',
    NAME VARCHAR(20) NOT NULL COMMENT '성명',
    MOBILE_NUMBER VARCHAR(11) NOT NULL COMMENT '휴대폰 번호',
    STATUS VARCHAR(10) NOT NULL COMMENT '상태 (ACTIVE: 정상, DELETED: 탈퇴)',
    VERSION INT COMMENT '수정 버전',
    CREATED DATE COMMENT '생성일',
    UPDATED DATE COMMENT '수정일',
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(ID)
);


