# server
server:
  port: 10010
  servlet:
    context-path: ams

# spring
spring:
  # webflux
  webflux:
    base-path: ams
  # r2dbc
  r2dbc:

    url: r2dbc:mariadb://maria-database.ciroumm1ym9r.ap-northeast-2.rds.amazonaws.com:3306
    name: AMS
    username: admin
    password: admin1234
    pool:
      max-size: 100
      validation-query: SELECT 1

# logging
logging:
  level:
    org.springframework.r2dbc: DEBUG