# server
server:
  port: 10010
  servlet:
    context-path: ams
# spring
spring:
  profiles:
    active: h2
  # webflux
  webflux:
    base-path: ams
  # r2dbc
  r2dbc:
    pool:
      max-size: 100
      validation-query: SELECT 1
# logging
logging:
  level:
    org.springframework.r2dbc: DEBUG

---

spring:
  config:
    activate:
      on-profile: h2
  r2dbc:
    url: r2dbc:h2:file:///~/h2/ams;DB_CLOSE_ON_EXIT=TRUE;FILE_LOCK=NO
    username: admin
    password: admin1234

---

spring:
  config:
    activate:
      on-profile: aws
  r2dbc:
    url: r2dbc:mariadb://maria-database.ciroumm1ym9r.ap-northeast-2.rds.amazonaws.com:3306
    name: AMS
    username: admin
    password: admin1234