# spring
spring:
  # r2dbc
  r2dbc:
    url: r2dbc:mariadb://maria-database-1.ciroumm1ym9r.ap-northeast-2.rds.amazonaws.com:3306
    name: EMS
    username: admin
    password: admin1234
    pool:
      max-size: 100
      validation-query: SELECT 1

# logging
logging:
  level:
    org.springframework.r2dbc: DEBUG